### ISSUE TITLE
Question: Why all variables have wtd at the beginning?

### ISSUE THREAD

**Issue by aminvakil** [while-true-do/ansible-role-srv_httpd#1]
First I'd like to thank you for writing this great playbook, it is well-secured, well-classified, etc.

But I just cannot understand why'd you put wtd_srv at the beginning of all variables?

**Comment by daniel-schier** [comment]
Hey,

if 3 roles are using the variable "user" for example, they will overwrite each other. With the prefix, we ensure, that you can use other roles in the same playbook. Therefore we have decided, that for our roles all variables will be prefixed with "wtd_role_name", for this role it is "wtd_srv_httpd".

You can read about this convention and other descisions here: https://github.com/while-true-do/ansible-skeleton/blob/master/docs/CONVENTION_ROLE.md
